services:
  review-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    container_name: "review-service"
    networks:
      - global-network

networks:
  global-network:
    name: global-network
    external: true
    driver: bridge
