spring:
  profiles:
    active: default
  application:
    name: ${SPRING_APP_NAME:review-service}
  datasource:
    url: jdbc:postgresql://postgresql:5432/reviews
    username: "user123"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
server:
  port: 8890
  servlet:
    context-path: /api
logging:
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
management:
  endpoints:
    web:
      exposure:
        include=*: